diary/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello/', include('hello.urls', namespace='hello')),
    url(r'^register/', include('register.urls', namespace='register'))
]

hello/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.hello, name='hello'),
]

register/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.regist_data, name='regist_data'),
    url(r'^index/$', views.index, name='index'),
    url(r'^today/$', views.today, name='today'),
    url(r'^get_query/$', views.get_query, name='get_query'),
]

register/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.


def hello(request):
    return HttpResponse('Jesus Kingdom!')

register/views.py
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def regist_data(request):
    return HttpResponse('Jesus Kingdom!')

def today(request):
    message = 'Today\'s schedule is'

    d = {
        'message': message,
    }
    return render(request, 'today.html', d)

def get_query(request):
    # d = {
    #     'subject': request.POST('subject'),
    #     'content': request.POST('content'),
    # }
    if request.POST.get('subject') is not None \
            or request.POST.get('content') is not None:
        d = {
            'subject': request.POST.get('subject'),
            'content': request.POST.get('content'),
        }
    else:
        d = {}

    return render(request, 'get_query.html', d)


def index(request):
    if datetime.now().hour in range(18, 23) \
        or datetime.now().hour in range(0,6):
        message = 'Good Evening!'
    elif datetime.now().hour in range(7,11):
        message = 'Good Morning!'
    else:
        message = 'Good Afternoon!'

    d = {
        'hour': datetime.now().hour,
        'minute': datetime.now().minute,
        'message': message,
    }
    return render(request, 'index.html', d)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/get_query.html
{% extends "base.html" %}

{% block body %}
    <div>
        <form action="" method="post">
            <label>題名:<input type="text" size="20" name="subject"></label><br>
            <label>内容:<input type="text" size="20" name="content"></label>
            {% csrf_token %}
            <input type="submit" value="送信">
        </form>
        {% if subject %}
            Subject: {{ subject }}<br>
        {% endif %}
        {% if content %}
            Content: {{ content }}
        {% endif %}
    </div>
    <div>
        <a href="{% url 'register:index' %}">index</a><br>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block body %}
    <div>
        {{message}}<br>
        {{hour}}時{{minute}}分です.
    </div>
    <div>
        <a href="{% url 'register:today' %}">today</a><br>
        <a href="{% url 'register:get_query' %}">get_query</a><br>
    </div>
{% endblock %}

templates/today.html
{% extends "base.html" %}

{% block body %}
    <div>
    {{ message }} <br>
    </div>
    <div>
        <a href="{% url 'register:index' %}">index</a><br>
        <a href="https://www.youtube.com/watch?v=43D_nBGfuGY&index=8&list=RDxXA5StMti8c">Mr. Children 365日</a>
    </div>
{% endblock %}